In [1]:
#Question 1
import numpy as np
array=np.random.random(size=(10,1))
print(array)
mean=array.mean()
print(mean)

[[0.74401277]
 [0.69085035]
 [0.10373186]
 [0.85639471]
 [0.44363927]
 [0.17495955]
 [0.90566084]
 [0.62773069]
 [0.57825357]
 [0.06667168]]
0.5191905274865155


In [2]:
#Question 2
array1=np.random.random(size=(20,1))
print(array1)
var=array1.var()
std=array1.std()
print(var)
print(std)

[[0.57876478]
 [0.95497982]
 [0.08595124]
 [0.52634805]
 [0.35497764]
 [0.98861078]
 [0.94944707]
 [0.89193313]
 [0.34420404]
 [0.2939417 ]
 [0.01598239]
 [0.57027426]
 [0.04218754]
 [0.61451858]
 [0.60786242]
 [0.62224732]
 [0.91197066]
 [0.95164762]
 [0.85214422]
 [0.36678681]]
0.09775828652673675
0.3126632158197327


In [3]:
#Question 3
arr=np.random.random(size=(10,20))
arr1=np.random.random(size=(20,25))
arr2=np.matmul(arr,arr1)
print(arr2)
arr2.sum()

[[6.67430574 5.2510548  4.79799013 5.50668994 5.27037169 6.95431414
  4.86287302 4.59478427 5.70442286 5.38898537 5.18253722 5.17127294
  4.92853348 5.11728215 6.02819383 6.26900861 5.73128022 5.47632248
  4.95057931 4.13951178 6.11578962 4.29468762 4.54482985 5.88322412
  5.61078184]
 [6.16207037 4.33769122 4.11070558 4.85708595 3.96621547 6.58057193
  4.75035494 4.40074321 5.30176331 4.66719939 3.7651929  4.83177863
  4.20830345 4.17807701 4.79797453 5.53706673 4.60106922 4.94778879
  4.59424526 3.82222125 5.50558937 3.10459065 4.34867589 5.20564807
  4.10089177]
 [4.34203975 4.6957969  3.42646634 3.84219678 3.17246077 5.01719275
  4.05823874 4.08687624 4.1778027  3.19630873 4.095233   2.62526571
  2.41523248 3.36814417 4.17086983 3.95799839 3.86349089 3.97369385
  3.78774284 3.79401399 4.19718273 3.00193739 3.75992448 4.02979508
  3.84738963]
 [7.74458636 6.4066373  4.74774469 6.75679769 5.54344157 8.11031157
  6.23331995 6.24094484 6.98077729 6.58954935 5.6167284  5.78440504
  6.04

1147.8668356892517

In [4]:
#Question 4
array2=np.random.random(size=(10,1))
print(array2)
print("*"*80)
array3=np.ndarray((10,1))
def func(x):
    return 1/1+ np.exp(-x)
List=list()
List1=list()
for i in range(0,array2.shape[0]):
    List.clear()
    for j in array2[i]:
        List.append(func(j))
    List1.append(List)
print(List1)
np.array(List1)

[[0.59670574]
 [0.91403547]
 [0.82186518]
 [0.16018917]
 [0.90031309]
 [0.37355905]
 [0.74291194]
 [0.44466325]
 [0.91045001]
 [0.49005824]]
********************************************************************************
[[1.612590717940014], [1.612590717940014], [1.612590717940014], [1.612590717940014], [1.612590717940014], [1.612590717940014], [1.612590717940014], [1.612590717940014], [1.612590717940014], [1.612590717940014]]


array([[1.61259072],
       [1.61259072],
       [1.61259072],
       [1.61259072],
       [1.61259072],
       [1.61259072],
       [1.61259072],
       [1.61259072],
       [1.61259072],
       [1.61259072]])